name:                Connect4
version:             0.1.0.0
github:              "MariaEduardaDeAzevedo/Connect4"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/MariaEduardaDeAzevedo/Connect4#readme>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  runConnect4:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Connect4
